#!/bin/bash
roll=chef-server
cd /tmp

# update/upgrade apt-get
apt-get update -y
apt-get upgrade -y

# install chef
wget https://packages.chef.io/stable/ubuntu/16.04/chef-server-core_12.11.0-1_amd64.deb
dpkg -i chef-server*
