#!/bin/bash
roll=chef-server
cd /tmp

# update/upgrade apt-get
apt-get update -y
apt-get upgrade -y

# ensure host name resolves
printf "127.0.0.1\tlocalhost\n" > /tmp/hosts
printf "$(ip -o -f inet address show eth0 | cut -d ' ' -f 7 | cut -d '/' -f 1)\t$(hostname)\n\n" >> /tmp/hosts
grep -e '#' -A 99 /etc/hosts >> /tmp/hosts
echo /tmp/hosts > /etc/hosts

# install chef
wget https://packages.chef.io/stable/ubuntu/16.04/chef-server-core_12.11.0-1_amd64.deb
dpkg -i chef-server*
cp /opt/opscode/embedded/service/omnibus-ctl/spec/fixtures/pivotal.pem /etc/opscode/.
chef-server-ctl reconfigure
